### ISSUE TITLE
AttributeError: module 'onmt' has no attribute 'Translator'

### ISSUE THREAD

**Issue by loveJasmine** [marcotcr/sears#1]
mldl@ub1604:~/ub16_prj/sears$ python3 Computing_SEARs_for_sentiment_analysis.py 
GPU ID 0
Traceback (most recent call last):
  File "Computing_SEARs_for_sentiment_analysis.py", line 32, in <module>
    ps = paraphrase_scorer.ParaphraseScorer(gpu_id=0)
  File "sears/paraphrase_scorer.py", line 64, in __init__
    translator = onmt_model.OnmtModel(f, gpu_id)
  File "sears/onmt_model.py", line 103, in __init__
    self.translator = onmt.Translator(opt)
AttributeError: module 'onmt' has no attribute 'Translator'
mldl@ub1604:~/ub16_prj/sears$

**Comment by marcotcr** [comment]
Did you install onmt from my fork according to the instructions?

**Comment by loveJasmine** [comment]
“onmt from my fork according to the instructions” ---where is it？

**Comment by marcotcr** [comment]
[here](https://github.com/marcotcr/sears#installation)
