### ISSUE TITLE
Notebook for computing SEARs for machine comprehension

### ISSUE THREAD

**Issue by ziyaoh** [marcotcr/sears#2]
Hi,

Thank you for publishing this code! Right now the only notebook is for sentiment analysis. I'm wondering if there's another notebook available to compute SEARs for machine comprehension? I imagine there might be some differences between these two tasks. If so, that would be great if you could provide that notebook as well.

Otherwise, I can try to modify the existing notebook to compute SEARs for machine comprehension myself. In this case, I have several questions:

1. What dataset did you use to compute SEAs for machine comprehension task? Is it SQUAD? Does it matter which dataset to use at all?
2. How did you define an adversarial question for machine comprehension problem? For sentiment analysis it's easy because the prediction is either positive or negative, and flip of correct prediction means that machine make it wrong. However, machine comprehension problem can have multiple reasonable answers. So how did you define a flip for machine comprehension?

Thank you so much for your time!
Ziyao

**Comment by ziyaoh** [comment]
Or if you have the precomputed SEARs for machine comprehension available that would be even better! :)

**Comment by marcotcr** [comment]
Hi. The notebook for SEARs is pretty much the same, the difference being how we define the predict and flip functions, and how we handle the data (it's pairs instead of single texts).

> What dataset did you use to compute SEAs for machine comprehension task? Is it SQUAD? Does it matter which dataset to use at all?

Yes, it was SQuAD. The dataset matters in the sense that the generated SEAs will be examples from the dataset with small changes.

> How did you define an adversarial question for machine comprehension problem? For sentiment analysis it's easy because the prediction is either positive or negative, and flip of correct prediction means that machine make it wrong. However, machine comprehension problem can have multiple reasonable answers. So how did you define a flip for machine comprehension?

Assuming q is the original question and q' is the adversary, (q, q') is a flip if the answer to q is in the correct answer set and q' is not (i.e. it went from right to wrong).

Here is a set of SEARs we found using AllenNLP on SQuAD (flips 7% of predictions). Not that not all of them are good, which is why we still use a human in the loop to accept or reject rules.
```
What VBZ -> What 's
What NOUN -> Which NOUN
did -> does
What VERB DET -> What is DET
What VERB DET -> What 's DET
WP VBZ DET -> WP are DET
WP VBZ -> WP is
is the -> 's the
WP is -> WP 's
What VERB -> So what VERB
What is DET -> What 's the
is the -> are the
What VBD -> And what VBD
WP VBZ the -> WP 's the
What VBZ DET -> What are DET
WP is DET -> What 's DET 
```

**Comment by ziyaoh** [comment]
Thank you for the response! Just two more quick questions though:

1. Did you use SQUAD train set or dev set to compute the sears? How many paragraph-question pairs did you use to compute it?
2. Did you use the same parameters for machine comprehension as for sentiment analysis?

I modified the existing notebook to compute sears for machine comprehension using 9000 paragraph-question pairs out of the total 10570 pairs from SQUAD dev set. But I couldn't get any rules, since every rule candidate is disqualified, either because the 10th percentile score is lower than threshold or the number of flips is smaller than 6. I'm wondering whether it's because the number of input I'm using is too small.

**Comment by marcotcr** [comment]
1. Dev set. All of the paragraph-question pairs that were predicted correctly by AllenNLP, for a total of about 7000 pairs I think.
2. Same parameters.

 The rules I've shared flip between 39 and 139 instances. Can you get SEARs for sentiment analysis? I'm wondering if there is some problem with the similarity scoring.

**Comment by ziyaoh** [comment]
Thank you for the information! I ran the existing notebook before and got SEARs for sentiment analysis, so scoring should be ok. I just found that there was a stupid mistake in the code I made which might be the reason for this issue. I have fixed the mistake and recomputing the SEARs.

I also want to confirm your definition for correct answer set. Is it the set of all the answers presented in SQUAD for each pair?

**Comment by ziyaoh** [comment]
I have one last question: do you remember how long did it take you to compute SEARs for machine comprehension? Was it several days or weeks?

**Comment by marcotcr** [comment]
Sorry, I thought I had answered this. 
> I also want to confirm your definition for correct answer set. Is it the set of all the answers presented in SQUAD for each pair?

Yes.

>I have one last question: do you remember how long did it take you to compute SEARs for machine comprehension? Was it several days or weeks?

About a day, but I have access to a machine with a good gpu.
