### ISSUE TITLE
Using AllenNLP model in SEARs computation

### ISSUE THREAD

**Issue by ziyaoh** [marcotcr/sears#4]
I'm trying to compute SEARs for machine comprehension task, and need to load the pretrained AllenNLP model for this purpose. However, [the AllenNLP project](https://github.com/allenai/allennlp) has different dependency than your sears project. For example, AllenNLP requires python 3.6 with pytorch 0.4, while sears uses python 3.5 with pytorch 0.2.

How do I use make them working at the same time? I tried to set up a local server for AllenNLP and send http requests from sears, but it seems really slow. Did you make your own implementation? Any help will be really appreciated!

Ziyao

**Comment by marcotcr** [comment]
I also set up a local server, but made sure to batch requests rather than send them one at a time.

**Comment by ziyaoh** [comment]
Hi, thank you for your help! I have struggled for weeks to optimize my script for MC SEARs computation, but it's still unacceptably slow even on GPU. I did a line profiling and seems two bottlenecks are allennlp querying and similarity scoring. Even with batch requests for allennlp it's still taking a lot of time, and similarity scoring seem taking even longer than requesting.

At this point, I think it would be best if you could provide your original notebook for this task so that I could learn what I did wrong. I would really really appreciate it!!

**Comment by marcotcr** [comment]
So actually I did something dumber than a local server, I ran their binary in batches. 
Here is how I ran AllenNLP:
```
def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]
def predict_fn(data, batch_size=1000):
    zdata = data
    out = []
    for data in chunks(data, batch_size):
        fz = open('/tmp/fazzzzo.jsonl', 'w')
        for d in data:
            fz.write('%s\n'% json.dumps(d))
        fz.close()
        cmd = 'source /home/marcotcr/.bashrc; source activate allennlp;python -m allennlp.run predict https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz /tmp/fazzzzo.jsonl --output-file /tmp/outputzzzz2 --silent --cuda-device 1'
        subprocess.call(cmd, shell=True, executable='/bin/bash')
        for line in open('/tmp/outputzzzz2', 'r'):
            l = json.loads(line)
            r = l['best_span_str']
            out.append(r)
    return np.array(out)
```
For comparison sake, running `ans = predict_fn(data)` where data is every question in the squad 1.1 dev set takes me 1202 seconds. Is that similar to what you're getting?

**Comment by ziyaoh** [comment]
Thank you for sharing this! Just one more question: do you remember what was the size of your frequent_rules after extracting rules step from the flips? I got about 2 million of them. Is this about right?

**Comment by marcotcr** [comment]
Sorry, I would have to rerun the notebook to get that and it's too much trouble right now. Frequent rules is typically huge (2M does not sound wrong), but after filtering by rule_flips (rule_flips > 35, which is 0.5%) we got about 4,000 rules.

**Comment by ziyaoh** [comment]
Hi Macro, sorry to bother you again. I think I have tried everything to make this work but it still doesn't. I tried running the binary in batches as you did, and it took around 300 seconds to complete for squad dev set. Querying single local server took only about 80 seconds on the same GPU. I set up 4 servers to serve the SEARs computation at the same time but it still took me 3 days to finish up the querying step. Even then, the prediction cache and other lists/dicts are so large that they won't fit in memory... That's the reason I asked about the number of frequent rules you got, as the sentiment analysis generated only 200k rules.

This has been a really frustrating process and the result has been delayed for months from our plan. I'm thinking if it's possible for me to take a look at your original notebook. You can send it to my email at yaozi326@outlook.com if that works best for you. This could save us a lot of time, and I would be very very very appreciated!!!

**Comment by marcotcr** [comment]
Argh, sorry this is so hard. We can continue this conversation via email then.
